name: Check-PR-Files
on:
  pull_request_target:
    types: [opened]

jobs:
  check-pr-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/check-pr-files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}